apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  creationTimestamp: "2022-12-13T14:25:34Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "31021"
  uid: 601ae5b3-f363-4a74-a0dc-e5bae18735e3
data:
  policy.csv: |
    p, role:deploy-role, applications, sync, wordpress/wordpress, allow
    p, role:deploy-role, applications, update, wordpress/wordpress, allow
    g, deploy, role:deploy-role
  policy.default: role:readonly