apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: argocd-cluster
  region: eu-north-1

vpc:
  subnets:
    private:
      eu-north-1a: { id: subnet-01f96629aff291d23 }
      eu-north-1b: { id: subnet-0c7f8785a02c52280 }
      eu-north-1c: { id: subnet-0d1e28adf48d52921 }

nodeGroups:
  - name: ng-1-agrocd
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
