version: "3.9"  # optional since v1.27.0
services:
  web:
    image: nginx:1.18-alpine
    volumes:
      - ./config:/etc/nginx/conf.d:ro
    ports:
      - 80:80

  db:
    # Using mariadb this time'
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    env_file:
      - .env
    volumes:
      - my_db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    env_file:
      - .env
    restart: always
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
volumes:
  my_db_data:
  wordpress:
  